### ISSUE TITLE
heroku have JSON issues

### ISSUE THREAD

**Issue by algesten** [ProjectMoon/reed#10]
Unsure whether this is heroku or reed issue. I installed reed on a node.js installation (coffee-script actually) on heroku. However the server crashes with:

```
2011-12-11T22:32:38+00:00 app[web.1]: SyntaxError: Unexpected token ILLEGAL
2011-12-11T22:32:38+00:00 app[web.1]:     at Object.parse (native)  
2011-12-11T22:32:38+00:00 app[web.1]:     at Command.callback (/app/node_modules/reed/lib/reed.js:377:19) 
2011-12-11T22:32:38+00:00 app[web.1]:     at RedisClient.flush_and_error (/app/node_modules/reed/node_modules/redis/index.js:105:25)
```

It's as if JSON is not a valid object. But then it is supposed to be on V8, right?!... confused.

**Comment by algesten** [comment]
Could it be that heroku runs a too old version of node.js? (0.4.7)

```
376         client.hget(key, "metadata", function(err, metadata) {
377                 metadata = JSON.parse(metadata);
378                 if (typeof(metadata) !== "undefined" && metadata != null && Object.keys(metadata).length > 0) {
```

**Comment by algesten** [comment]
I realise I was reading the stack trace wrong. The problem is that we're sending something bad into `JSON.parse()`. Potentially this could be because I have no metadata in my md files (no Title: or Author:).

I fixed it by putting an if around:

```
if (typeof(metadata) !== "undefined" && metadata != null) {
    metadata = JSON.parse(metadata);
}
```

**Comment by ProjectMoon** [comment]
That's probably what it is. All the articles on my site have metadata so I never really tested other cases. If you submit a pull request, I can integrate the fix.

**Comment by ProjectMoon** [comment]
Actually the better way to fix this would be a try-catch. I will add it tomorrow.

**Comment by ProjectMoon** [comment]
Added in 54f68b12ab432354575ae7c6437c4c6b79edeeb6
