### ISSUE TITLE
Allow client auth, possibly by URL

### ISSUE THREAD

**Issue by algesten** [ProjectMoon/reed#12]
936e361 is what I ended up doing to use reed on heroku. This is obviously too vendor specific `process.env.REDISTOGO_URL` but the question is - what is the _correct_ way of solving this problem?
1. We need some configuration setting for host/port/auth.
2. It would be nice to support URLs like the one shown - perhaps another config setting?

Thoughts?

**Comment by algesten** [comment]
So 936e361 - f2f5aa4 - fb4c637 may be going in a possible direction.

Basically you have to set 'redisUrl' on the reed object before calling `open()`.

To finish it off one should probably have a `redisPassword` for good measure. But is it a good way to go?

**Comment by ProjectMoon** [comment]
The way I was planning on doing this is wrapping around the redis API here: https://github.com/mranney/node_redis

It will involve sending in a configuration object to reed, probably via a `configure` method. For sure, those options would contain user, password, host, and port. It would call `auth` if user and password are present.

**Comment by algesten** [comment]
The redis-url package I used to configure for heroku is very very lightweight. It wouldn't be much addition to support configuring either via url or explicit props.

https://github.com/ddollar/redis-url/blob/master/index.js

So what you're saying is that you'd do pretty much what I've done, but rather than setting the config on the reed object, they would be passed in via a config() method?

M

**Comment by ProjectMoon** [comment]
The redis-url module creates the client in its own way. If possible, I'd like reed to create the client in only one way.

And yes, it would be a configure method like so:

``` javascript
reed.configure({
    host: 'myhost',
    port: 123,
    user: 'myuser',
    password: 'mypass'
});
```

This method would either be on the main reed object, or in a separate config namespace, e.g.: `reed.config.configure()`. This is similar to how express works, and how I've designed my other libraries (aka flux).

**Comment by algesten** [comment]
If you don't mind I'd like to take a stab at this.

**Comment by ProjectMoon** [comment]
It should be pretty straightforward. The host and port would need to be stored as variables, and then passed into createClient when it is called. The username and password, if existing, would need to call `client.auth`.

**Comment by algesten** [comment]
Yep, I'm almost done. Just doing some testing.

M
