### ISSUE TITLE
Allow for published date in metadata

### ISSUE THREAD

**Issue by algesten** [ProjectMoon/reed#16]
I sometimes go back to my blog posts and correct spelling mistakes, formatting etc. I would like to a a way to specify the publishing date so that future sort order is not affected by these edits.

One way would be to allow a user defined date in the meta data: `PublishedDate: 2011-05-23`  

I believe this means the stored entries in Redis need to have a separate field `PublishedDate` which it uses for sorting, while the `LastModified` is for checking freshness. The default would be to set `PublishedDate` to the first `LastModified` it encounters for an file.

**Comment by ProjectMoon** [comment]
This can be done already. Just use a user-defined date and a call to `sort` on a list of posts returned from `reed.all`. The only thing that would be a possible problem is the fact that all the metadata is considered to be strings. So you'd have to catch that in your sorting. Easy enough though.

``` javascript
reed.all(function(err, posts) {
    posts.sort(function(a, b) {
        if (a.metadata.publishedDate === b.metadata.publishedDate) {
            return 0;
        }
        else if (new Date(a.metadata.publishedDate) > new Date(b.metadata.publishedDate)) {
            return 1;
        }
        else {
            return -1;
        }
    });
});
```

Or something like that anyway. I think you can do boolean comparisons on dates.

**Comment by algesten** [comment]
Your right! And I was already doing that... sometimes :)

Apparently it's too late. I'm off to bed. Thanks for your time.
